# Generated by Django 2.2 on 2019-04-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundery',
            name='state',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
