# Generated by Django 2.2 on 2019-04-05 18:52

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0002_boundery_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boundery',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='boundery',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
