# Generated by Django 2.2 on 2019-04-08 14:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0003_auto_20190405_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundery',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, dim=3, null=True, srid=4326),
        ),
    ]
