# Generated by Django 2.2 on 2019-04-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0006_boundery_matchingid'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundery',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boundery',
            name='processedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
