# Generated by Django 2.2 on 2019-05-10 17:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0007_auto_20190422_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formattedAddress', models.CharField(blank=True, max_length=256, null=True)),
                ('fullAddress', django.contrib.postgres.fields.jsonb.JSONField()),
                ('matchingId', models.CharField(blank=True, max_length=256, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('processedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('boundery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polygons.Boundery')),
            ],
        ),
    ]
