# Generated by Django 2.2 on 2019-05-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0008_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='matchingId',
        ),
    ]
