# Generated by Django 2.2 on 2019-05-10 18:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0009_remove_address_matchingid'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='confidence',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
